### ISSUE TITLE
As a business, I want Herald users to have a Herald account with personal information, so that I can better serve them as a customer.

### ISSUE THREAD

**Issue by dlowrey** [heraldtech/herald-android#1]
- [x] Epic [?](https://www.atlassian.com/agile/project-management/epics)
- [ ] User Story [?](https://www.atlassian.com/agile/project-management/user-stories) 

__Details__
Users should have accounts with personal information in them so that businesses can use that information to better serve them as customers.

__Acceptance Criteria__
A user can create, login to, edit, update, and completely delete their account. 

__Tasks__
- [ ] break down into user stories and reference this epic 

*related issues will appear in the discussion below as they are referenced*
