### ISSUE TITLE
As a user, I want to be able to view the businesses that give me discounts for using Herald, so that I can partake in them and visit the business.

### ISSUE THREAD

**Issue by dlowrey** [heraldtech/herald-android#2]
- [x] Epic [?](https://www.atlassian.com/agile/project-management/epics)
- [ ] User Story [?](https://www.atlassian.com/agile/project-management/user-stories) 

__Details__
A user should have motivation to download and keep this application on their devices, so Herald should give businesses the opportunity to offer discounts and other services for Herald users directly through the application. This will hopefully encourage adoption of the application for mutual benefit.

__Acceptance Criteria__
This epic is complete when a user can select a business from the Herald application and see available discounts specific to Herald users. 

__Tasks__
- [ ] Break into user stories and reference this epic

*related issues will appear in the discussion below as they are referenced*
