### ISSUE TITLE
As Herald Technologies, I want any application to have an adequate customer feedback feature, so that Herald users have the opportunity to reach out.

### ISSUE THREAD

**Issue by dlowrey** [heraldtech/herald-android#3]
- [x] Epic [?](https://www.atlassian.com/agile/project-management/epics)
- [ ] User Story [?](https://www.atlassian.com/agile/project-management/user-stories) 

__Details__
Users should feel like they can reach out with feedback and for help/problems. 

__Acceptance Criteria__
There is a dedicated screen/section in the application that allows users to fill out some necessary information and then submit feedback.

__Tasks__
- [ ] Create user stories and reference this epic

*related issues will appear in the discussion below as they are refrenced*
