### ISSUE TITLE
As a business, I want to be notified when and about any Herald user that walks into my store, so that I can better serve them as a customer.

### ISSUE THREAD

**Issue by dlowrey** [heraldtech/herald-android#4]
- [x] Epic [?](https://www.atlassian.com/agile/project-management/epics)
- [ ] User Story [?](https://www.atlassian.com/agile/project-management/user-stories) 

__Details__
Business want to provide excellent customer service, tailored to each unique customer. They need a way to know who is in there store so they can provide next-level customer service to them. 

__Acceptance Criteria__
This epic is complete when a business using Herald Tech gets notified when and about a user that has entered their store/place of business.

__Tasks__
- [ ] Create user stories and reference this epic

*related issues will appear in the discussion below as they are refrenced*
